language: go
go:
  - 1.15.x
dist: trusty
sudo: true
addons:
  ssh_known_hosts:
    - 163.172.133.90
before_install:
  - openssl aes-256-cbc -K $encrypted_db2095f63ba3_key -iv $encrypted_db2095f63ba3_iv
    -in deployments/deploy_rsa.enc -out deployments/deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - cp deployments/deploy_rsa ~/.ssh/deploy_rsa
  - chmod 600 ~/.ssh/deploy_rsa
  - ssh-add ~/.ssh/deploy_rsa
  - sudo apt install -y wget unzip
  - pushd /home/travis
  - wget https://github.com/protocolbuffers/protobuf/releases/download/v3.12.0/protoc-3.12.0-linux-x86_64.zip
  - unzip protoc-3.12.0-linux-x86_64.zip
  - bin/protoc --version
  - popd
  - cd $TRAVIS_BUILD_DIR/deployments && make all
install:
  - echo "Installed"
after_success:
  - echo "OK"
  - make build
script:
  - cd $TRAVIS_BUILD_DIR/deployments
  - make run-tests
  - make run-linters
#git:
#  depth: 9999999
#deploy:
#  - provider: script
#    skip_cleanup: true
#    script: $TRAVIS_BUILD_DIR/deployments/deploy.sh
#    on:
#      branch: master
#branches:
#  only:
#    - master
#    - develop