// Code generated by protoc-gen-go. DO NOT EDIT.
// source: search.proto

package search

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type UserSearch struct {
	Username             string   `protobuf:"bytes,1,opt,name=Username,proto3" json:"Username,omitempty"`
	Last                 int32    `protobuf:"varint,2,opt,name=Last,proto3" json:"Last,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserSearch) Reset()         { *m = UserSearch{} }
func (m *UserSearch) String() string { return proto.CompactTextString(m) }
func (*UserSearch) ProtoMessage()    {}
func (*UserSearch) Descriptor() ([]byte, []int) {
	return fileDescriptor_453745cff914010e, []int{0}
}

func (m *UserSearch) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserSearch.Unmarshal(m, b)
}
func (m *UserSearch) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserSearch.Marshal(b, m, deterministic)
}
func (m *UserSearch) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserSearch.Merge(m, src)
}
func (m *UserSearch) XXX_Size() int {
	return xxx_messageInfo_UserSearch.Size(m)
}
func (m *UserSearch) XXX_DiscardUnknown() {
	xxx_messageInfo_UserSearch.DiscardUnknown(m)
}

var xxx_messageInfo_UserSearch proto.InternalMessageInfo

func (m *UserSearch) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *UserSearch) GetLast() int32 {
	if m != nil {
		return m.Last
	}
	return 0
}

type User struct {
	Id                   int64    `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Username             string   `protobuf:"bytes,2,opt,name=Username,proto3" json:"Username,omitempty"`
	Avatar               string   `protobuf:"bytes,3,opt,name=Avatar,proto3" json:"Avatar,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_453745cff914010e, []int{1}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *User) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *User) GetAvatar() string {
	if m != nil {
		return m.Avatar
	}
	return ""
}

type Users struct {
	Users                []*User  `protobuf:"bytes,1,rep,name=Users,proto3" json:"Users,omitempty"`
	Error                int32    `protobuf:"varint,2,opt,name=Error,proto3" json:"Error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Users) Reset()         { *m = Users{} }
func (m *Users) String() string { return proto.CompactTextString(m) }
func (*Users) ProtoMessage()    {}
func (*Users) Descriptor() ([]byte, []int) {
	return fileDescriptor_453745cff914010e, []int{2}
}

func (m *Users) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Users.Unmarshal(m, b)
}
func (m *Users) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Users.Marshal(b, m, deterministic)
}
func (m *Users) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Users.Merge(m, src)
}
func (m *Users) XXX_Size() int {
	return xxx_messageInfo_Users.Size(m)
}
func (m *Users) XXX_DiscardUnknown() {
	xxx_messageInfo_Users.DiscardUnknown(m)
}

var xxx_messageInfo_Users proto.InternalMessageInfo

func (m *Users) GetUsers() []*User {
	if m != nil {
		return m.Users
	}
	return nil
}

func (m *Users) GetError() int32 {
	if m != nil {
		return m.Error
	}
	return 0
}

type PinSearch struct {
	Title                string   `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Last                 int32    `protobuf:"varint,2,opt,name=last,proto3" json:"last,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PinSearch) Reset()         { *m = PinSearch{} }
func (m *PinSearch) String() string { return proto.CompactTextString(m) }
func (*PinSearch) ProtoMessage()    {}
func (*PinSearch) Descriptor() ([]byte, []int) {
	return fileDescriptor_453745cff914010e, []int{3}
}

func (m *PinSearch) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PinSearch.Unmarshal(m, b)
}
func (m *PinSearch) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PinSearch.Marshal(b, m, deterministic)
}
func (m *PinSearch) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PinSearch.Merge(m, src)
}
func (m *PinSearch) XXX_Size() int {
	return xxx_messageInfo_PinSearch.Size(m)
}
func (m *PinSearch) XXX_DiscardUnknown() {
	xxx_messageInfo_PinSearch.DiscardUnknown(m)
}

var xxx_messageInfo_PinSearch proto.InternalMessageInfo

func (m *PinSearch) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *PinSearch) GetLast() int32 {
	if m != nil {
		return m.Last
	}
	return 0
}

type Pin struct {
	Id                   int64    `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=Title,proto3" json:"Title,omitempty"`
	Content              string   `protobuf:"bytes,3,opt,name=Content,proto3" json:"Content,omitempty"`
	PictureHeight        int32    `protobuf:"varint,4,opt,name=PictureHeight,proto3" json:"PictureHeight,omitempty"`
	PictureWidth         int32    `protobuf:"varint,5,opt,name=PictureWidth,proto3" json:"PictureWidth,omitempty"`
	ImgLink              string   `protobuf:"bytes,6,opt,name=ImgLink,proto3" json:"ImgLink,omitempty"`
	UserId               int32    `protobuf:"varint,7,opt,name=UserId,proto3" json:"UserId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Pin) Reset()         { *m = Pin{} }
func (m *Pin) String() string { return proto.CompactTextString(m) }
func (*Pin) ProtoMessage()    {}
func (*Pin) Descriptor() ([]byte, []int) {
	return fileDescriptor_453745cff914010e, []int{4}
}

func (m *Pin) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pin.Unmarshal(m, b)
}
func (m *Pin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pin.Marshal(b, m, deterministic)
}
func (m *Pin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pin.Merge(m, src)
}
func (m *Pin) XXX_Size() int {
	return xxx_messageInfo_Pin.Size(m)
}
func (m *Pin) XXX_DiscardUnknown() {
	xxx_messageInfo_Pin.DiscardUnknown(m)
}

var xxx_messageInfo_Pin proto.InternalMessageInfo

func (m *Pin) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Pin) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Pin) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *Pin) GetPictureHeight() int32 {
	if m != nil {
		return m.PictureHeight
	}
	return 0
}

func (m *Pin) GetPictureWidth() int32 {
	if m != nil {
		return m.PictureWidth
	}
	return 0
}

func (m *Pin) GetImgLink() string {
	if m != nil {
		return m.ImgLink
	}
	return ""
}

func (m *Pin) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type Pins struct {
	Pins                 []*Pin   `protobuf:"bytes,1,rep,name=Pins,proto3" json:"Pins,omitempty"`
	Error                int32    `protobuf:"varint,2,opt,name=Error,proto3" json:"Error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Pins) Reset()         { *m = Pins{} }
func (m *Pins) String() string { return proto.CompactTextString(m) }
func (*Pins) ProtoMessage()    {}
func (*Pins) Descriptor() ([]byte, []int) {
	return fileDescriptor_453745cff914010e, []int{5}
}

func (m *Pins) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pins.Unmarshal(m, b)
}
func (m *Pins) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pins.Marshal(b, m, deterministic)
}
func (m *Pins) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pins.Merge(m, src)
}
func (m *Pins) XXX_Size() int {
	return xxx_messageInfo_Pins.Size(m)
}
func (m *Pins) XXX_DiscardUnknown() {
	xxx_messageInfo_Pins.DiscardUnknown(m)
}

var xxx_messageInfo_Pins proto.InternalMessageInfo

func (m *Pins) GetPins() []*Pin {
	if m != nil {
		return m.Pins
	}
	return nil
}

func (m *Pins) GetError() int32 {
	if m != nil {
		return m.Error
	}
	return 0
}

type BoardSearch struct {
	Title                string   `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Last                 int32    `protobuf:"varint,2,opt,name=last,proto3" json:"last,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BoardSearch) Reset()         { *m = BoardSearch{} }
func (m *BoardSearch) String() string { return proto.CompactTextString(m) }
func (*BoardSearch) ProtoMessage()    {}
func (*BoardSearch) Descriptor() ([]byte, []int) {
	return fileDescriptor_453745cff914010e, []int{6}
}

func (m *BoardSearch) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BoardSearch.Unmarshal(m, b)
}
func (m *BoardSearch) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BoardSearch.Marshal(b, m, deterministic)
}
func (m *BoardSearch) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BoardSearch.Merge(m, src)
}
func (m *BoardSearch) XXX_Size() int {
	return xxx_messageInfo_BoardSearch.Size(m)
}
func (m *BoardSearch) XXX_DiscardUnknown() {
	xxx_messageInfo_BoardSearch.DiscardUnknown(m)
}

var xxx_messageInfo_BoardSearch proto.InternalMessageInfo

func (m *BoardSearch) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *BoardSearch) GetLast() int32 {
	if m != nil {
		return m.Last
	}
	return 0
}

type Board struct {
	Id                   int64    `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=Title,proto3" json:"Title,omitempty"`
	Content              string   `protobuf:"bytes,3,opt,name=Content,proto3" json:"Content,omitempty"`
	Username             string   `protobuf:"bytes,4,opt,name=Username,proto3" json:"Username,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Board) Reset()         { *m = Board{} }
func (m *Board) String() string { return proto.CompactTextString(m) }
func (*Board) ProtoMessage()    {}
func (*Board) Descriptor() ([]byte, []int) {
	return fileDescriptor_453745cff914010e, []int{7}
}

func (m *Board) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Board.Unmarshal(m, b)
}
func (m *Board) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Board.Marshal(b, m, deterministic)
}
func (m *Board) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Board.Merge(m, src)
}
func (m *Board) XXX_Size() int {
	return xxx_messageInfo_Board.Size(m)
}
func (m *Board) XXX_DiscardUnknown() {
	xxx_messageInfo_Board.DiscardUnknown(m)
}

var xxx_messageInfo_Board proto.InternalMessageInfo

func (m *Board) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Board) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Board) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *Board) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

type Boards struct {
	Boards               []*Board `protobuf:"bytes,1,rep,name=Boards,proto3" json:"Boards,omitempty"`
	Error                int32    `protobuf:"varint,2,opt,name=Error,proto3" json:"Error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Boards) Reset()         { *m = Boards{} }
func (m *Boards) String() string { return proto.CompactTextString(m) }
func (*Boards) ProtoMessage()    {}
func (*Boards) Descriptor() ([]byte, []int) {
	return fileDescriptor_453745cff914010e, []int{8}
}

func (m *Boards) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Boards.Unmarshal(m, b)
}
func (m *Boards) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Boards.Marshal(b, m, deterministic)
}
func (m *Boards) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Boards.Merge(m, src)
}
func (m *Boards) XXX_Size() int {
	return xxx_messageInfo_Boards.Size(m)
}
func (m *Boards) XXX_DiscardUnknown() {
	xxx_messageInfo_Boards.DiscardUnknown(m)
}

var xxx_messageInfo_Boards proto.InternalMessageInfo

func (m *Boards) GetBoards() []*Board {
	if m != nil {
		return m.Boards
	}
	return nil
}

func (m *Boards) GetError() int32 {
	if m != nil {
		return m.Error
	}
	return 0
}

func init() {
	proto.RegisterType((*UserSearch)(nil), "search.UserSearch")
	proto.RegisterType((*User)(nil), "search.User")
	proto.RegisterType((*Users)(nil), "search.Users")
	proto.RegisterType((*PinSearch)(nil), "search.PinSearch")
	proto.RegisterType((*Pin)(nil), "search.Pin")
	proto.RegisterType((*Pins)(nil), "search.Pins")
	proto.RegisterType((*BoardSearch)(nil), "search.BoardSearch")
	proto.RegisterType((*Board)(nil), "search.Board")
	proto.RegisterType((*Boards)(nil), "search.Boards")
}

func init() {
	proto.RegisterFile("search.proto", fileDescriptor_453745cff914010e)
}

var fileDescriptor_453745cff914010e = []byte{
	// 425 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xa4, 0x53, 0x4d, 0x6f, 0xda, 0x40,
	0x10, 0xad, 0xf1, 0x07, 0x65, 0xb0, 0x51, 0xbb, 0xad, 0x2a, 0x8b, 0x4b, 0xab, 0x55, 0x2b, 0x71,
	0xe2, 0x00, 0x42, 0x55, 0xa5, 0xe6, 0x00, 0x11, 0x4a, 0x88, 0x50, 0x84, 0x4c, 0xa2, 0x9c, 0x1d,
	0xb3, 0x02, 0x2b, 0x60, 0x47, 0xeb, 0x0d, 0x12, 0x7f, 0x2c, 0xf7, 0xfc, 0xb3, 0xec, 0xce, 0xae,
	0x23, 0x3b, 0xe1, 0x12, 0xe5, 0xc4, 0xbc, 0xe7, 0x79, 0xb3, 0xf3, 0x9e, 0x06, 0xf0, 0x0b, 0x16,
	0xf3, 0x64, 0xd3, 0xbf, 0xe7, 0xb9, 0xc8, 0x89, 0xa7, 0x11, 0xfd, 0x0f, 0x70, 0x5d, 0x30, 0xbe,
	0x44, 0x44, 0xba, 0xf0, 0x59, 0xa1, 0x2c, 0xde, 0xb1, 0xd0, 0xfa, 0x65, 0xf5, 0x5a, 0xd1, 0x0b,
	0x26, 0x04, 0x9c, 0x79, 0x5c, 0x88, 0xb0, 0x21, 0x79, 0x37, 0xc2, 0x9a, 0x5e, 0x80, 0xa3, 0xbe,
	0x93, 0x0e, 0x34, 0x66, 0x2b, 0x54, 0xd8, 0x91, 0xac, 0x6a, 0x73, 0x1a, 0xaf, 0xe6, 0xfc, 0x00,
	0x6f, 0xbc, 0x8f, 0x45, 0xcc, 0x43, 0x1b, 0xbf, 0x18, 0x44, 0xc7, 0xe0, 0xaa, 0x9e, 0x82, 0x50,
	0x53, 0xc8, 0x79, 0x76, 0xaf, 0x3d, 0xf0, 0xfb, 0x66, 0x71, 0x45, 0x46, 0xa6, 0xe7, 0x3b, 0xb8,
	0x53, 0xce, 0x73, 0x6e, 0xb6, 0xd1, 0x80, 0x8e, 0xa0, 0xb5, 0x48, 0x33, 0xe3, 0x45, 0xb6, 0x88,
	0x54, 0x6c, 0x4b, 0x23, 0x1a, 0x28, 0x17, 0xdb, 0x8a, 0x0b, 0x55, 0xd3, 0x27, 0x0b, 0x6c, 0xa9,
	0x7b, 0xe3, 0x42, 0x4e, 0xb8, 0xc2, 0x09, 0xda, 0x82, 0x06, 0x24, 0x84, 0xe6, 0x69, 0x9e, 0x09,
	0x96, 0x09, 0x63, 0xa0, 0x84, 0xe4, 0x37, 0x04, 0x8b, 0x34, 0x11, 0x0f, 0x9c, 0x9d, 0xb3, 0x74,
	0xbd, 0x11, 0xa1, 0x83, 0x8f, 0xd4, 0x49, 0x69, 0xcf, 0x37, 0xc4, 0x4d, 0xba, 0x12, 0x9b, 0xd0,
	0xc5, 0xa6, 0x1a, 0xa7, 0xde, 0x98, 0xed, 0xd6, 0xf3, 0x34, 0xbb, 0x0b, 0x3d, 0xfd, 0x86, 0x81,
	0x2a, 0x3d, 0x95, 0x80, 0xdc, 0xb3, 0x89, 0x3a, 0x83, 0xe8, 0x09, 0x38, 0xd2, 0x42, 0x41, 0x7e,
	0xea, 0x5f, 0x93, 0x5d, 0xbb, 0xcc, 0x4e, 0x72, 0x91, 0x6e, 0x38, 0x9e, 0xdc, 0x5f, 0x68, 0x4f,
	0xf2, 0x98, 0xaf, 0xde, 0x9d, 0x5d, 0x02, 0x2e, 0x0a, 0x3f, 0x1c, 0x5e, 0xf5, 0x64, 0x9c, 0xfa,
	0xc9, 0xd0, 0x29, 0x78, 0xf8, 0x48, 0x41, 0xfe, 0x94, 0x95, 0x31, 0x18, 0x94, 0x06, 0x91, 0x8d,
	0xca, 0xb6, 0xa3, 0x26, 0x07, 0x8f, 0x16, 0x04, 0xda, 0xe0, 0x92, 0xf1, 0x7d, 0x9a, 0x30, 0x32,
	0x82, 0xce, 0x19, 0x13, 0x78, 0x52, 0x93, 0xc3, 0x25, 0x5e, 0x79, 0xf5, 0xda, 0x74, 0x73, 0x37,
	0xa8, 0x72, 0x05, 0xfd, 0x44, 0x86, 0x28, 0x53, 0x71, 0x4e, 0x0e, 0xda, 0xd7, 0xd7, 0x4a, 0xd0,
	0x46, 0xe5, 0x57, 0x28, 0x25, 0xfa, 0x07, 0x5f, 0xa4, 0x48, 0x2f, 0x58, 0xca, 0xbe, 0xd5, 0xd6,
	0x37, 0xc2, 0x4e, 0x8d, 0x94, 0xd2, 0x5b, 0x0f, 0xff, 0xb3, 0xc3, 0xe7, 0x00, 0x00, 0x00, 0xff,
	0xff, 0x92, 0x0d, 0x00, 0xd0, 0xc3, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// SearchServiceClient is the client API for SearchService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SearchServiceClient interface {
	GetUsersByName(ctx context.Context, in *UserSearch, opts ...grpc.CallOption) (*Users, error)
	GetPinsByTitle(ctx context.Context, in *PinSearch, opts ...grpc.CallOption) (*Pins, error)
	GetBoardsByTitle(ctx context.Context, in *BoardSearch, opts ...grpc.CallOption) (*Boards, error)
}

type searchServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSearchServiceClient(cc grpc.ClientConnInterface) SearchServiceClient {
	return &searchServiceClient{cc}
}

func (c *searchServiceClient) GetUsersByName(ctx context.Context, in *UserSearch, opts ...grpc.CallOption) (*Users, error) {
	out := new(Users)
	err := c.cc.Invoke(ctx, "/search.SearchService/GetUsersByName", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *searchServiceClient) GetPinsByTitle(ctx context.Context, in *PinSearch, opts ...grpc.CallOption) (*Pins, error) {
	out := new(Pins)
	err := c.cc.Invoke(ctx, "/search.SearchService/GetPinsByTitle", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *searchServiceClient) GetBoardsByTitle(ctx context.Context, in *BoardSearch, opts ...grpc.CallOption) (*Boards, error) {
	out := new(Boards)
	err := c.cc.Invoke(ctx, "/search.SearchService/GetBoardsByTitle", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SearchServiceServer is the server API for SearchService service.
type SearchServiceServer interface {
	GetUsersByName(context.Context, *UserSearch) (*Users, error)
	GetPinsByTitle(context.Context, *PinSearch) (*Pins, error)
	GetBoardsByTitle(context.Context, *BoardSearch) (*Boards, error)
}

// UnimplementedSearchServiceServer can be embedded to have forward compatible implementations.
type UnimplementedSearchServiceServer struct {
}

func (*UnimplementedSearchServiceServer) GetUsersByName(ctx context.Context, req *UserSearch) (*Users, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUsersByName not implemented")
}
func (*UnimplementedSearchServiceServer) GetPinsByTitle(ctx context.Context, req *PinSearch) (*Pins, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPinsByTitle not implemented")
}
func (*UnimplementedSearchServiceServer) GetBoardsByTitle(ctx context.Context, req *BoardSearch) (*Boards, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBoardsByTitle not implemented")
}

func RegisterSearchServiceServer(s *grpc.Server, srv SearchServiceServer) {
	s.RegisterService(&_SearchService_serviceDesc, srv)
}

func _SearchService_GetUsersByName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserSearch)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchServiceServer).GetUsersByName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/search.SearchService/GetUsersByName",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchServiceServer).GetUsersByName(ctx, req.(*UserSearch))
	}
	return interceptor(ctx, in, info, handler)
}

func _SearchService_GetPinsByTitle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PinSearch)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchServiceServer).GetPinsByTitle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/search.SearchService/GetPinsByTitle",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchServiceServer).GetPinsByTitle(ctx, req.(*PinSearch))
	}
	return interceptor(ctx, in, info, handler)
}

func _SearchService_GetBoardsByTitle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BoardSearch)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchServiceServer).GetBoardsByTitle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/search.SearchService/GetBoardsByTitle",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchServiceServer).GetBoardsByTitle(ctx, req.(*BoardSearch))
	}
	return interceptor(ctx, in, info, handler)
}

var _SearchService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "search.SearchService",
	HandlerType: (*SearchServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUsersByName",
			Handler:    _SearchService_GetUsersByName_Handler,
		},
		{
			MethodName: "GetPinsByTitle",
			Handler:    _SearchService_GetPinsByTitle_Handler,
		},
		{
			MethodName: "GetBoardsByTitle",
			Handler:    _SearchService_GetBoardsByTitle_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "search.proto",
}
