// Code generated by MockGen. DO NOT EDIT.
// Source: repository.go

// Package mock_user is a generated GoMock package.
package mock_user

import (
	api "github.com/go-park-mail-ru/2020_2_Eternity/api"
	domain "github.com/go-park-mail-ru/2020_2_Eternity/pkg/domain"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockIRepository is a mock of IRepository interface
type MockIRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIRepositoryMockRecorder
}

// MockIRepositoryMockRecorder is the mock recorder for MockIRepository
type MockIRepositoryMockRecorder struct {
	mock *MockIRepository
}

// NewMockIRepository creates a new mock instance
func NewMockIRepository(ctrl *gomock.Controller) *MockIRepository {
	mock := &MockIRepository{ctrl: ctrl}
	mock.recorder = &MockIRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockIRepository) EXPECT() *MockIRepositoryMockRecorder {
	return m.recorder
}

// CreateUser mocks base method
func (m *MockIRepository) CreateUser(user *api.SignUp) (*domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", user)
	ret0, _ := ret[0].(*domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUser indicates an expected call of CreateUser
func (mr *MockIRepositoryMockRecorder) CreateUser(user interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockIRepository)(nil).CreateUser), user)
}

// GetUser mocks base method
func (m *MockIRepository) GetUser(id int) (*domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUser", id)
	ret0, _ := ret[0].(*domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUser indicates an expected call of GetUser
func (mr *MockIRepositoryMockRecorder) GetUser(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUser", reflect.TypeOf((*MockIRepository)(nil).GetUser), id)
}

// GetUserByName mocks base method
func (m *MockIRepository) GetUserByName(username string) (*domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByName", username)
	ret0, _ := ret[0].(*domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByName indicates an expected call of GetUserByName
func (mr *MockIRepositoryMockRecorder) GetUserByName(username interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByName", reflect.TypeOf((*MockIRepository)(nil).GetUserByName), username)
}

// GetUserByNameWithFollowers mocks base method
func (m *MockIRepository) GetUserByNameWithFollowers(username string) (*domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByNameWithFollowers", username)
	ret0, _ := ret[0].(*domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByNameWithFollowers indicates an expected call of GetUserByNameWithFollowers
func (mr *MockIRepositoryMockRecorder) GetUserByNameWithFollowers(username interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByNameWithFollowers", reflect.TypeOf((*MockIRepository)(nil).GetUserByNameWithFollowers), username)
}

// UpdateUser mocks base method
func (m *MockIRepository) UpdateUser(id int, profile *api.UpdateUser) (*domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUser", id, profile)
	ret0, _ := ret[0].(*domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateUser indicates an expected call of UpdateUser
func (mr *MockIRepositoryMockRecorder) UpdateUser(id, profile interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUser", reflect.TypeOf((*MockIRepository)(nil).UpdateUser), id, profile)
}

// UpdatePassword mocks base method
func (m *MockIRepository) UpdatePassword(id int, psswd string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePassword", id, psswd)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdatePassword indicates an expected call of UpdatePassword
func (mr *MockIRepositoryMockRecorder) UpdatePassword(id, psswd interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePassword", reflect.TypeOf((*MockIRepository)(nil).UpdatePassword), id, psswd)
}

// UpdateAvatar mocks base method
func (m *MockIRepository) UpdateAvatar(id int, avatar string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAvatar", id, avatar)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateAvatar indicates an expected call of UpdateAvatar
func (mr *MockIRepositoryMockRecorder) UpdateAvatar(id, avatar interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAvatar", reflect.TypeOf((*MockIRepository)(nil).UpdateAvatar), id, avatar)
}

// GetAvatar mocks base method
func (m *MockIRepository) GetAvatar(id int) (error, string) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAvatar", id)
	ret0, _ := ret[0].(error)
	ret1, _ := ret[1].(string)
	return ret0, ret1
}

// GetAvatar indicates an expected call of GetAvatar
func (mr *MockIRepositoryMockRecorder) GetAvatar(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAvatar", reflect.TypeOf((*MockIRepository)(nil).GetAvatar), id)
}

// Follow mocks base method
func (m *MockIRepository) Follow(following, id int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Follow", following, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Follow indicates an expected call of Follow
func (mr *MockIRepositoryMockRecorder) Follow(following, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Follow", reflect.TypeOf((*MockIRepository)(nil).Follow), following, id)
}

// UnFollow mocks base method
func (m *MockIRepository) UnFollow(unfollowing, id int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnFollow", unfollowing, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// UnFollow indicates an expected call of UnFollow
func (mr *MockIRepositoryMockRecorder) UnFollow(unfollowing, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnFollow", reflect.TypeOf((*MockIRepository)(nil).UnFollow), unfollowing, id)
}

// GetFollowers mocks base method
func (m *MockIRepository) GetFollowers(username string) ([]domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFollowers", username)
	ret0, _ := ret[0].([]domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFollowers indicates an expected call of GetFollowers
func (mr *MockIRepositoryMockRecorder) GetFollowers(username interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFollowers", reflect.TypeOf((*MockIRepository)(nil).GetFollowers), username)
}

// GetFollowing mocks base method
func (m *MockIRepository) GetFollowing(username string) ([]domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFollowing", username)
	ret0, _ := ret[0].([]domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFollowing indicates an expected call of GetFollowing
func (mr *MockIRepositoryMockRecorder) GetFollowing(username interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFollowing", reflect.TypeOf((*MockIRepository)(nil).GetFollowing), username)
}
