// Code generated by MockGen. DO NOT EDIT.
// Source: usecase.go

// Package mock_feed is a generated GoMock package.
package mock_feed

import (
	domain "github.com/go-park-mail-ru/2020_2_Eternity/pkg/domain"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockIUseCase is a mock of IUseCase interface
type MockIUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockIUseCaseMockRecorder
}

// MockIUseCaseMockRecorder is the mock recorder for MockIUseCase
type MockIUseCaseMockRecorder struct {
	mock *MockIUseCase
}

// NewMockIUseCase creates a new mock instance
func NewMockIUseCase(ctrl *gomock.Controller) *MockIUseCase {
	mock := &MockIUseCase{ctrl: ctrl}
	mock.recorder = &MockIUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockIUseCase) EXPECT() *MockIUseCaseMockRecorder {
	return m.recorder
}

// GetFeed mocks base method
func (m *MockIUseCase) GetFeed(userId, last int) ([]domain.PinResp, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFeed", userId, last)
	ret0, _ := ret[0].([]domain.PinResp)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFeed indicates an expected call of GetFeed
func (mr *MockIUseCaseMockRecorder) GetFeed(userId, last interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFeed", reflect.TypeOf((*MockIUseCase)(nil).GetFeed), userId, last)
}
