// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.6.1
// source: pkg/proto/chat/chat.proto

package chat

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type ChatCreateReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId         int32  `protobuf:"varint,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	CollocutorName string `protobuf:"bytes,2,opt,name=CollocutorName,proto3" json:"CollocutorName,omitempty"`
}

func (x *ChatCreateReq) Reset() {
	*x = ChatCreateReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_chat_chat_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChatCreateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatCreateReq) ProtoMessage() {}

func (x *ChatCreateReq) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_chat_chat_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatCreateReq.ProtoReflect.Descriptor instead.
func (*ChatCreateReq) Descriptor() ([]byte, []int) {
	return file_pkg_proto_chat_chat_proto_rawDescGZIP(), []int{0}
}

func (x *ChatCreateReq) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ChatCreateReq) GetCollocutorName() string {
	if x != nil {
		return x.CollocutorName
	}
	return ""
}

type GetChatByIdReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId int32 `protobuf:"varint,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	ChatId int32 `protobuf:"varint,2,opt,name=ChatId,proto3" json:"ChatId,omitempty"`
}

func (x *GetChatByIdReq) Reset() {
	*x = GetChatByIdReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_chat_chat_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetChatByIdReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChatByIdReq) ProtoMessage() {}

func (x *GetChatByIdReq) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_chat_chat_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChatByIdReq.ProtoReflect.Descriptor instead.
func (*GetChatByIdReq) Descriptor() ([]byte, []int) {
	return file_pkg_proto_chat_chat_proto_rawDescGZIP(), []int{1}
}

func (x *GetChatByIdReq) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetChatByIdReq) GetChatId() int32 {
	if x != nil {
		return x.ChatId
	}
	return 0
}

type Id struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int32 `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
}

func (x *Id) Reset() {
	*x = Id{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_chat_chat_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Id) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Id) ProtoMessage() {}

func (x *Id) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_chat_chat_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Id.ProtoReflect.Descriptor instead.
func (*Id) Descriptor() ([]byte, []int) {
	return file_pkg_proto_chat_chat_proto_rawDescGZIP(), []int{2}
}

func (x *Id) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type MarkMessagesReadReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId int32 `protobuf:"varint,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	ChatId int32 `protobuf:"varint,2,opt,name=ChatId,proto3" json:"ChatId,omitempty"`
}

func (x *MarkMessagesReadReq) Reset() {
	*x = MarkMessagesReadReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_chat_chat_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MarkMessagesReadReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkMessagesReadReq) ProtoMessage() {}

func (x *MarkMessagesReadReq) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_chat_chat_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkMessagesReadReq.ProtoReflect.Descriptor instead.
func (*MarkMessagesReadReq) Descriptor() ([]byte, []int) {
	return file_pkg_proto_chat_chat_proto_rawDescGZIP(), []int{3}
}

func (x *MarkMessagesReadReq) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *MarkMessagesReadReq) GetChatId() int32 {
	if x != nil {
		return x.ChatId
	}
	return 0
}

type CreateMessageReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId  int32  `protobuf:"varint,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	ChatId  int32  `protobuf:"varint,2,opt,name=ChatId,proto3" json:"ChatId,omitempty"`
	Content string `protobuf:"bytes,3,opt,name=Content,proto3" json:"Content,omitempty"`
}

func (x *CreateMessageReq) Reset() {
	*x = CreateMessageReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_chat_chat_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateMessageReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMessageReq) ProtoMessage() {}

func (x *CreateMessageReq) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_chat_chat_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMessageReq.ProtoReflect.Descriptor instead.
func (*CreateMessageReq) Descriptor() ([]byte, []int) {
	return file_pkg_proto_chat_chat_proto_rawDescGZIP(), []int{4}
}

func (x *CreateMessageReq) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreateMessageReq) GetChatId() int32 {
	if x != nil {
		return x.ChatId
	}
	return 0
}

func (x *CreateMessageReq) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type GetLastNMessagesReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId    int32 `protobuf:"varint,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	ChatId    int32 `protobuf:"varint,2,opt,name=ChatId,proto3" json:"ChatId,omitempty"`
	NMessages int32 `protobuf:"varint,3,opt,name=NMessages,proto3" json:"NMessages,omitempty"`
}

func (x *GetLastNMessagesReq) Reset() {
	*x = GetLastNMessagesReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_chat_chat_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetLastNMessagesReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLastNMessagesReq) ProtoMessage() {}

func (x *GetLastNMessagesReq) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_chat_chat_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLastNMessagesReq.ProtoReflect.Descriptor instead.
func (*GetLastNMessagesReq) Descriptor() ([]byte, []int) {
	return file_pkg_proto_chat_chat_proto_rawDescGZIP(), []int{5}
}

func (x *GetLastNMessagesReq) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetLastNMessagesReq) GetChatId() int32 {
	if x != nil {
		return x.ChatId
	}
	return 0
}

func (x *GetLastNMessagesReq) GetNMessages() int32 {
	if x != nil {
		return x.NMessages
	}
	return 0
}

type GetNMessagesReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId    int32 `protobuf:"varint,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	ChatId    int32 `protobuf:"varint,2,opt,name=ChatId,proto3" json:"ChatId,omitempty"`
	NMessages int32 `protobuf:"varint,3,opt,name=NMessages,proto3" json:"NMessages,omitempty"`
	MessageId int32 `protobuf:"varint,4,opt,name=MessageId,proto3" json:"MessageId,omitempty"`
}

func (x *GetNMessagesReq) Reset() {
	*x = GetNMessagesReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_chat_chat_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetNMessagesReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNMessagesReq) ProtoMessage() {}

func (x *GetNMessagesReq) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_chat_chat_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNMessagesReq.ProtoReflect.Descriptor instead.
func (*GetNMessagesReq) Descriptor() ([]byte, []int) {
	return file_pkg_proto_chat_chat_proto_rawDescGZIP(), []int{6}
}

func (x *GetNMessagesReq) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetNMessagesReq) GetChatId() int32 {
	if x != nil {
		return x.ChatId
	}
	return 0
}

func (x *GetNMessagesReq) GetNMessages() int32 {
	if x != nil {
		return x.NMessages
	}
	return 0
}

func (x *GetNMessagesReq) GetMessageId() int32 {
	if x != nil {
		return x.MessageId
	}
	return 0
}

type MessageRespArray struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Messages []*MessageResp `protobuf:"bytes,1,rep,name=Messages,proto3" json:"Messages,omitempty"`
}

func (x *MessageRespArray) Reset() {
	*x = MessageRespArray{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_chat_chat_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageRespArray) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageRespArray) ProtoMessage() {}

func (x *MessageRespArray) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_chat_chat_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageRespArray.ProtoReflect.Descriptor instead.
func (*MessageRespArray) Descriptor() ([]byte, []int) {
	return file_pkg_proto_chat_chat_proto_rawDescGZIP(), []int{7}
}

func (x *MessageRespArray) GetMessages() []*MessageResp {
	if x != nil {
		return x.Messages
	}
	return nil
}

type MessageResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id             int32                `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Content        string               `protobuf:"bytes,2,opt,name=Content,proto3" json:"Content,omitempty"`
	CreationTime   *timestamp.Timestamp `protobuf:"bytes,3,opt,name=CreationTime,proto3" json:"CreationTime,omitempty"`
	ChatId         int32                `protobuf:"varint,4,opt,name=ChatId,proto3" json:"ChatId,omitempty"`
	UserName       string               `protobuf:"bytes,5,opt,name=UserName,proto3" json:"UserName,omitempty"`
	UserAvatarLink string               `protobuf:"bytes,6,opt,name=UserAvatarLink,proto3" json:"UserAvatarLink,omitempty"`
}

func (x *MessageResp) Reset() {
	*x = MessageResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_chat_chat_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageResp) ProtoMessage() {}

func (x *MessageResp) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_chat_chat_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageResp.ProtoReflect.Descriptor instead.
func (*MessageResp) Descriptor() ([]byte, []int) {
	return file_pkg_proto_chat_chat_proto_rawDescGZIP(), []int{8}
}

func (x *MessageResp) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *MessageResp) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *MessageResp) GetCreationTime() *timestamp.Timestamp {
	if x != nil {
		return x.CreationTime
	}
	return nil
}

func (x *MessageResp) GetChatId() int32 {
	if x != nil {
		return x.ChatId
	}
	return 0
}

func (x *MessageResp) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *MessageResp) GetUserAvatarLink() string {
	if x != nil {
		return x.UserAvatarLink
	}
	return ""
}

type ChatRespArray struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Chats []*ChatResp `protobuf:"bytes,1,rep,name=Chats,proto3" json:"Chats,omitempty"`
}

func (x *ChatRespArray) Reset() {
	*x = ChatRespArray{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_chat_chat_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChatRespArray) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatRespArray) ProtoMessage() {}

func (x *ChatRespArray) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_chat_chat_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatRespArray.ProtoReflect.Descriptor instead.
func (*ChatRespArray) Descriptor() ([]byte, []int) {
	return file_pkg_proto_chat_chat_proto_rawDescGZIP(), []int{9}
}

func (x *ChatRespArray) GetChats() []*ChatResp {
	if x != nil {
		return x.Chats
	}
	return nil
}

type ChatResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id                   int32                `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	CreationTime         *timestamp.Timestamp `protobuf:"bytes,2,opt,name=CreationTime,proto3" json:"CreationTime,omitempty"`
	LastMsgContent       string               `protobuf:"bytes,3,opt,name=LastMsgContent,proto3" json:"LastMsgContent,omitempty"`
	LastMsgUsername      string               `protobuf:"bytes,4,opt,name=LastMsgUsername,proto3" json:"LastMsgUsername,omitempty"`
	LastMsgTime          *timestamp.Timestamp `protobuf:"bytes,5,opt,name=LastMsgTime,proto3" json:"LastMsgTime,omitempty"`
	CollocutorName       string               `protobuf:"bytes,6,opt,name=CollocutorName,proto3" json:"CollocutorName,omitempty"`
	CollocutorAvatarLink string               `protobuf:"bytes,7,opt,name=CollocutorAvatarLink,proto3" json:"CollocutorAvatarLink,omitempty"`
	NewMessages          int32                `protobuf:"varint,8,opt,name=NewMessages,proto3" json:"NewMessages,omitempty"`
}

func (x *ChatResp) Reset() {
	*x = ChatResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_chat_chat_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChatResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatResp) ProtoMessage() {}

func (x *ChatResp) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_chat_chat_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatResp.ProtoReflect.Descriptor instead.
func (*ChatResp) Descriptor() ([]byte, []int) {
	return file_pkg_proto_chat_chat_proto_rawDescGZIP(), []int{10}
}

func (x *ChatResp) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ChatResp) GetCreationTime() *timestamp.Timestamp {
	if x != nil {
		return x.CreationTime
	}
	return nil
}

func (x *ChatResp) GetLastMsgContent() string {
	if x != nil {
		return x.LastMsgContent
	}
	return ""
}

func (x *ChatResp) GetLastMsgUsername() string {
	if x != nil {
		return x.LastMsgUsername
	}
	return ""
}

func (x *ChatResp) GetLastMsgTime() *timestamp.Timestamp {
	if x != nil {
		return x.LastMsgTime
	}
	return nil
}

func (x *ChatResp) GetCollocutorName() string {
	if x != nil {
		return x.CollocutorName
	}
	return ""
}

func (x *ChatResp) GetCollocutorAvatarLink() string {
	if x != nil {
		return x.CollocutorAvatarLink
	}
	return ""
}

func (x *ChatResp) GetNewMessages() int32 {
	if x != nil {
		return x.NewMessages
	}
	return 0
}

type WsMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId int32  `protobuf:"varint,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	Data   []byte `protobuf:"bytes,2,opt,name=Data,proto3" json:"Data,omitempty"`
}

func (x *WsMessage) Reset() {
	*x = WsMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_chat_chat_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WsMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WsMessage) ProtoMessage() {}

func (x *WsMessage) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_chat_chat_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WsMessage.ProtoReflect.Descriptor instead.
func (*WsMessage) Descriptor() ([]byte, []int) {
	return file_pkg_proto_chat_chat_proto_rawDescGZIP(), []int{11}
}

func (x *WsMessage) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *WsMessage) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_pkg_proto_chat_chat_proto protoreflect.FileDescriptor

var file_pkg_proto_chat_chat_proto_rawDesc = []byte{
	0x0a, 0x19, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x68, 0x61, 0x74,
	0x2f, 0x63, 0x68, 0x61, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x63, 0x68, 0x61,
	0x74, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x4f, 0x0a, 0x0d, 0x43, 0x68, 0x61, 0x74, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71,
	0x12, 0x16, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x26, 0x0a, 0x0e, 0x43, 0x6f, 0x6c, 0x6c,
	0x6f, 0x63, 0x75, 0x74, 0x6f, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0e, 0x43, 0x6f, 0x6c, 0x6c, 0x6f, 0x63, 0x75, 0x74, 0x6f, 0x72, 0x4e, 0x61, 0x6d, 0x65,
	0x22, 0x40, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x43, 0x68, 0x61, 0x74, 0x42, 0x79, 0x49, 0x64, 0x52,
	0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x43, 0x68,
	0x61, 0x74, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x43, 0x68, 0x61, 0x74,
	0x49, 0x64, 0x22, 0x14, 0x0a, 0x02, 0x49, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x49, 0x64, 0x22, 0x45, 0x0a, 0x13, 0x4d, 0x61, 0x72, 0x6b,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x52, 0x65, 0x61, 0x64, 0x52, 0x65, 0x71, 0x12,
	0x16, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x43, 0x68, 0x61, 0x74, 0x49,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x43, 0x68, 0x61, 0x74, 0x49, 0x64, 0x22,
	0x5c, 0x0a, 0x10, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x43,
	0x68, 0x61, 0x74, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x43, 0x68, 0x61,
	0x74, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x22, 0x63, 0x0a,
	0x13, 0x47, 0x65, 0x74, 0x4c, 0x61, 0x73, 0x74, 0x4e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x73, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06,
	0x43, 0x68, 0x61, 0x74, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x43, 0x68,
	0x61, 0x74, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x4e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x4e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x73, 0x22, 0x7d, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x4e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x73, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x16, 0x0a,
	0x06, 0x43, 0x68, 0x61, 0x74, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x43,
	0x68, 0x61, 0x74, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x4e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x4e, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x49, 0x64,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x49,
	0x64, 0x22, 0x41, 0x0a, 0x10, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x41, 0x72, 0x72, 0x61, 0x79, 0x12, 0x2d, 0x0a, 0x08, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x63, 0x68, 0x61, 0x74, 0x2e, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x52, 0x08, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x73, 0x22, 0xd3, 0x01, 0x0a, 0x0b, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x02, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x3e,
	0x0a, 0x0c, 0x43, 0x72, 0x65, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x52, 0x0c, 0x43, 0x72, 0x65, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x16,
	0x0a, 0x06, 0x43, 0x68, 0x61, 0x74, 0x49, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06,
	0x43, 0x68, 0x61, 0x74, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x55, 0x73, 0x65, 0x72, 0x4e, 0x61,
	0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x55, 0x73, 0x65, 0x72, 0x4e, 0x61,
	0x6d, 0x65, 0x12, 0x26, 0x0a, 0x0e, 0x55, 0x73, 0x65, 0x72, 0x41, 0x76, 0x61, 0x74, 0x61, 0x72,
	0x4c, 0x69, 0x6e, 0x6b, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x55, 0x73, 0x65, 0x72,
	0x41, 0x76, 0x61, 0x74, 0x61, 0x72, 0x4c, 0x69, 0x6e, 0x6b, 0x22, 0x35, 0x0a, 0x0d, 0x43, 0x68,
	0x61, 0x74, 0x52, 0x65, 0x73, 0x70, 0x41, 0x72, 0x72, 0x61, 0x79, 0x12, 0x24, 0x0a, 0x05, 0x43,
	0x68, 0x61, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x63, 0x68, 0x61,
	0x74, 0x2e, 0x43, 0x68, 0x61, 0x74, 0x52, 0x65, 0x73, 0x70, 0x52, 0x05, 0x43, 0x68, 0x61, 0x74,
	0x73, 0x22, 0xe8, 0x02, 0x0a, 0x08, 0x43, 0x68, 0x61, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x0e,
	0x0a, 0x02, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x49, 0x64, 0x12, 0x3e,
	0x0a, 0x0c, 0x43, 0x72, 0x65, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x52, 0x0c, 0x43, 0x72, 0x65, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x26,
	0x0a, 0x0e, 0x4c, 0x61, 0x73, 0x74, 0x4d, 0x73, 0x67, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x4c, 0x61, 0x73, 0x74, 0x4d, 0x73, 0x67, 0x43,
	0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x28, 0x0a, 0x0f, 0x4c, 0x61, 0x73, 0x74, 0x4d, 0x73,
	0x67, 0x55, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0f, 0x4c, 0x61, 0x73, 0x74, 0x4d, 0x73, 0x67, 0x55, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x3c, 0x0a, 0x0b, 0x4c, 0x61, 0x73, 0x74, 0x4d, 0x73, 0x67, 0x54, 0x69, 0x6d, 0x65, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x52, 0x0b, 0x4c, 0x61, 0x73, 0x74, 0x4d, 0x73, 0x67, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x26,
	0x0a, 0x0e, 0x43, 0x6f, 0x6c, 0x6c, 0x6f, 0x63, 0x75, 0x74, 0x6f, 0x72, 0x4e, 0x61, 0x6d, 0x65,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x43, 0x6f, 0x6c, 0x6c, 0x6f, 0x63, 0x75, 0x74,
	0x6f, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x32, 0x0a, 0x14, 0x43, 0x6f, 0x6c, 0x6c, 0x6f, 0x63,
	0x75, 0x74, 0x6f, 0x72, 0x41, 0x76, 0x61, 0x74, 0x61, 0x72, 0x4c, 0x69, 0x6e, 0x6b, 0x18, 0x07,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x14, 0x43, 0x6f, 0x6c, 0x6c, 0x6f, 0x63, 0x75, 0x74, 0x6f, 0x72,
	0x41, 0x76, 0x61, 0x74, 0x61, 0x72, 0x4c, 0x69, 0x6e, 0x6b, 0x12, 0x20, 0x0a, 0x0b, 0x4e, 0x65,
	0x77, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x18, 0x08, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x0b, 0x4e, 0x65, 0x77, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x22, 0x37, 0x0a, 0x09,
	0x57, 0x73, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x55, 0x73, 0x65,
	0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49,
	0x64, 0x12, 0x12, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x04, 0x44, 0x61, 0x74, 0x61, 0x32, 0xef, 0x03, 0x0a, 0x04, 0x43, 0x68, 0x61, 0x74, 0x12, 0x33,
	0x0a, 0x0a, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x68, 0x61, 0x74, 0x12, 0x13, 0x2e, 0x63,
	0x68, 0x61, 0x74, 0x2e, 0x43, 0x68, 0x61, 0x74, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65,
	0x71, 0x1a, 0x0e, 0x2e, 0x63, 0x68, 0x61, 0x74, 0x2e, 0x43, 0x68, 0x61, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x22, 0x00, 0x12, 0x35, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x43, 0x68, 0x61, 0x74, 0x42, 0x79,
	0x49, 0x64, 0x12, 0x14, 0x2e, 0x63, 0x68, 0x61, 0x74, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x68, 0x61,
	0x74, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x71, 0x1a, 0x0e, 0x2e, 0x63, 0x68, 0x61, 0x74, 0x2e,
	0x43, 0x68, 0x61, 0x74, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x12, 0x2f, 0x0a, 0x0c, 0x47, 0x65,
	0x74, 0x55, 0x73, 0x65, 0x72, 0x43, 0x68, 0x61, 0x74, 0x73, 0x12, 0x08, 0x2e, 0x63, 0x68, 0x61,
	0x74, 0x2e, 0x49, 0x64, 0x1a, 0x13, 0x2e, 0x63, 0x68, 0x61, 0x74, 0x2e, 0x43, 0x68, 0x61, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x41, 0x72, 0x72, 0x61, 0x79, 0x22, 0x00, 0x12, 0x47, 0x0a, 0x10, 0x4d,
	0x61, 0x72, 0x6b, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x52, 0x65, 0x61, 0x64, 0x12,
	0x19, 0x2e, 0x63, 0x68, 0x61, 0x74, 0x2e, 0x4d, 0x61, 0x72, 0x6b, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x73, 0x52, 0x65, 0x61, 0x64, 0x52, 0x65, 0x71, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70,
	0x74, 0x79, 0x22, 0x00, 0x12, 0x3c, 0x0a, 0x0d, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x16, 0x2e, 0x63, 0x68, 0x61, 0x74, 0x2e, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x11, 0x2e,
	0x63, 0x68, 0x61, 0x74, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x22, 0x00, 0x12, 0x33, 0x0a, 0x0d, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x12, 0x08, 0x2e, 0x63, 0x68, 0x61, 0x74, 0x2e, 0x49, 0x64, 0x1a, 0x16, 0x2e,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x12, 0x47, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x4c, 0x61,
	0x73, 0x74, 0x4e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x12, 0x19, 0x2e, 0x63, 0x68,
	0x61, 0x74, 0x2e, 0x47, 0x65, 0x74, 0x4c, 0x61, 0x73, 0x74, 0x4e, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x73, 0x52, 0x65, 0x71, 0x1a, 0x16, 0x2e, 0x63, 0x68, 0x61, 0x74, 0x2e, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x41, 0x72, 0x72, 0x61, 0x79, 0x22, 0x00,
	0x12, 0x45, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x4e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73,
	0x42, 0x65, 0x66, 0x6f, 0x72, 0x65, 0x12, 0x15, 0x2e, 0x63, 0x68, 0x61, 0x74, 0x2e, 0x47, 0x65,
	0x74, 0x4e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x52, 0x65, 0x71, 0x1a, 0x16, 0x2e,
	0x63, 0x68, 0x61, 0x74, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x41, 0x72, 0x72, 0x61, 0x79, 0x22, 0x00, 0x42, 0x3b, 0x5a, 0x39, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x67, 0x6f, 0x2d, 0x70, 0x61, 0x72, 0x6b, 0x2d, 0x6d, 0x61,
	0x69, 0x6c, 0x2d, 0x72, 0x75, 0x2f, 0x32, 0x30, 0x32, 0x30, 0x5f, 0x32, 0x5f, 0x45, 0x74, 0x65,
	0x72, 0x6e, 0x69, 0x74, 0x79, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f,
	0x63, 0x68, 0x61, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pkg_proto_chat_chat_proto_rawDescOnce sync.Once
	file_pkg_proto_chat_chat_proto_rawDescData = file_pkg_proto_chat_chat_proto_rawDesc
)

func file_pkg_proto_chat_chat_proto_rawDescGZIP() []byte {
	file_pkg_proto_chat_chat_proto_rawDescOnce.Do(func() {
		file_pkg_proto_chat_chat_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_proto_chat_chat_proto_rawDescData)
	})
	return file_pkg_proto_chat_chat_proto_rawDescData
}

var file_pkg_proto_chat_chat_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_pkg_proto_chat_chat_proto_goTypes = []interface{}{
	(*ChatCreateReq)(nil),       // 0: chat.ChatCreateReq
	(*GetChatByIdReq)(nil),      // 1: chat.GetChatByIdReq
	(*Id)(nil),                  // 2: chat.Id
	(*MarkMessagesReadReq)(nil), // 3: chat.MarkMessagesReadReq
	(*CreateMessageReq)(nil),    // 4: chat.CreateMessageReq
	(*GetLastNMessagesReq)(nil), // 5: chat.GetLastNMessagesReq
	(*GetNMessagesReq)(nil),     // 6: chat.GetNMessagesReq
	(*MessageRespArray)(nil),    // 7: chat.MessageRespArray
	(*MessageResp)(nil),         // 8: chat.MessageResp
	(*ChatRespArray)(nil),       // 9: chat.ChatRespArray
	(*ChatResp)(nil),            // 10: chat.ChatResp
	(*WsMessage)(nil),           // 11: chat.WsMessage
	(*timestamp.Timestamp)(nil), // 12: google.protobuf.Timestamp
	(*empty.Empty)(nil),         // 13: google.protobuf.Empty
}
var file_pkg_proto_chat_chat_proto_depIdxs = []int32{
	8,  // 0: chat.MessageRespArray.Messages:type_name -> chat.MessageResp
	12, // 1: chat.MessageResp.CreationTime:type_name -> google.protobuf.Timestamp
	10, // 2: chat.ChatRespArray.Chats:type_name -> chat.ChatResp
	12, // 3: chat.ChatResp.CreationTime:type_name -> google.protobuf.Timestamp
	12, // 4: chat.ChatResp.LastMsgTime:type_name -> google.protobuf.Timestamp
	0,  // 5: chat.Chat.CreateChat:input_type -> chat.ChatCreateReq
	1,  // 6: chat.Chat.GetChatById:input_type -> chat.GetChatByIdReq
	2,  // 7: chat.Chat.GetUserChats:input_type -> chat.Id
	3,  // 8: chat.Chat.MarkMessagesRead:input_type -> chat.MarkMessagesReadReq
	4,  // 9: chat.Chat.CreateMessage:input_type -> chat.CreateMessageReq
	2,  // 10: chat.Chat.DeleteMessage:input_type -> chat.Id
	5,  // 11: chat.Chat.GetLastNMessages:input_type -> chat.GetLastNMessagesReq
	6,  // 12: chat.Chat.GetNMessagesBefore:input_type -> chat.GetNMessagesReq
	10, // 13: chat.Chat.CreateChat:output_type -> chat.ChatResp
	10, // 14: chat.Chat.GetChatById:output_type -> chat.ChatResp
	9,  // 15: chat.Chat.GetUserChats:output_type -> chat.ChatRespArray
	13, // 16: chat.Chat.MarkMessagesRead:output_type -> google.protobuf.Empty
	8,  // 17: chat.Chat.CreateMessage:output_type -> chat.MessageResp
	13, // 18: chat.Chat.DeleteMessage:output_type -> google.protobuf.Empty
	7,  // 19: chat.Chat.GetLastNMessages:output_type -> chat.MessageRespArray
	7,  // 20: chat.Chat.GetNMessagesBefore:output_type -> chat.MessageRespArray
	13, // [13:21] is the sub-list for method output_type
	5,  // [5:13] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_pkg_proto_chat_chat_proto_init() }
func file_pkg_proto_chat_chat_proto_init() {
	if File_pkg_proto_chat_chat_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_proto_chat_chat_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChatCreateReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_chat_chat_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetChatByIdReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_chat_chat_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Id); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_chat_chat_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MarkMessagesReadReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_chat_chat_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateMessageReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_chat_chat_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetLastNMessagesReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_chat_chat_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetNMessagesReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_chat_chat_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessageRespArray); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_chat_chat_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessageResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_chat_chat_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChatRespArray); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_chat_chat_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChatResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_chat_chat_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WsMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_proto_chat_chat_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_proto_chat_chat_proto_goTypes,
		DependencyIndexes: file_pkg_proto_chat_chat_proto_depIdxs,
		MessageInfos:      file_pkg_proto_chat_chat_proto_msgTypes,
	}.Build()
	File_pkg_proto_chat_chat_proto = out.File
	file_pkg_proto_chat_chat_proto_rawDesc = nil
	file_pkg_proto_chat_chat_proto_goTypes = nil
	file_pkg_proto_chat_chat_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ChatClient is the client API for Chat service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ChatClient interface {
	CreateChat(ctx context.Context, in *ChatCreateReq, opts ...grpc.CallOption) (*ChatResp, error)
	//rpc RouteWs(stream WsMessage) returns (stream WsMessage) {}
	GetChatById(ctx context.Context, in *GetChatByIdReq, opts ...grpc.CallOption) (*ChatResp, error)
	GetUserChats(ctx context.Context, in *Id, opts ...grpc.CallOption) (*ChatRespArray, error)
	MarkMessagesRead(ctx context.Context, in *MarkMessagesReadReq, opts ...grpc.CallOption) (*empty.Empty, error)
	CreateMessage(ctx context.Context, in *CreateMessageReq, opts ...grpc.CallOption) (*MessageResp, error)
	DeleteMessage(ctx context.Context, in *Id, opts ...grpc.CallOption) (*empty.Empty, error)
	GetLastNMessages(ctx context.Context, in *GetLastNMessagesReq, opts ...grpc.CallOption) (*MessageRespArray, error)
	GetNMessagesBefore(ctx context.Context, in *GetNMessagesReq, opts ...grpc.CallOption) (*MessageRespArray, error)
}

type chatClient struct {
	cc grpc.ClientConnInterface
}

func NewChatClient(cc grpc.ClientConnInterface) ChatClient {
	return &chatClient{cc}
}

func (c *chatClient) CreateChat(ctx context.Context, in *ChatCreateReq, opts ...grpc.CallOption) (*ChatResp, error) {
	out := new(ChatResp)
	err := c.cc.Invoke(ctx, "/chat.Chat/CreateChat", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatClient) GetChatById(ctx context.Context, in *GetChatByIdReq, opts ...grpc.CallOption) (*ChatResp, error) {
	out := new(ChatResp)
	err := c.cc.Invoke(ctx, "/chat.Chat/GetChatById", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatClient) GetUserChats(ctx context.Context, in *Id, opts ...grpc.CallOption) (*ChatRespArray, error) {
	out := new(ChatRespArray)
	err := c.cc.Invoke(ctx, "/chat.Chat/GetUserChats", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatClient) MarkMessagesRead(ctx context.Context, in *MarkMessagesReadReq, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/chat.Chat/MarkMessagesRead", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatClient) CreateMessage(ctx context.Context, in *CreateMessageReq, opts ...grpc.CallOption) (*MessageResp, error) {
	out := new(MessageResp)
	err := c.cc.Invoke(ctx, "/chat.Chat/CreateMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatClient) DeleteMessage(ctx context.Context, in *Id, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/chat.Chat/DeleteMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatClient) GetLastNMessages(ctx context.Context, in *GetLastNMessagesReq, opts ...grpc.CallOption) (*MessageRespArray, error) {
	out := new(MessageRespArray)
	err := c.cc.Invoke(ctx, "/chat.Chat/GetLastNMessages", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatClient) GetNMessagesBefore(ctx context.Context, in *GetNMessagesReq, opts ...grpc.CallOption) (*MessageRespArray, error) {
	out := new(MessageRespArray)
	err := c.cc.Invoke(ctx, "/chat.Chat/GetNMessagesBefore", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ChatServer is the server API for Chat service.
type ChatServer interface {
	CreateChat(context.Context, *ChatCreateReq) (*ChatResp, error)
	//rpc RouteWs(stream WsMessage) returns (stream WsMessage) {}
	GetChatById(context.Context, *GetChatByIdReq) (*ChatResp, error)
	GetUserChats(context.Context, *Id) (*ChatRespArray, error)
	MarkMessagesRead(context.Context, *MarkMessagesReadReq) (*empty.Empty, error)
	CreateMessage(context.Context, *CreateMessageReq) (*MessageResp, error)
	DeleteMessage(context.Context, *Id) (*empty.Empty, error)
	GetLastNMessages(context.Context, *GetLastNMessagesReq) (*MessageRespArray, error)
	GetNMessagesBefore(context.Context, *GetNMessagesReq) (*MessageRespArray, error)
}

// UnimplementedChatServer can be embedded to have forward compatible implementations.
type UnimplementedChatServer struct {
}

func (*UnimplementedChatServer) CreateChat(context.Context, *ChatCreateReq) (*ChatResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateChat not implemented")
}
func (*UnimplementedChatServer) GetChatById(context.Context, *GetChatByIdReq) (*ChatResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetChatById not implemented")
}
func (*UnimplementedChatServer) GetUserChats(context.Context, *Id) (*ChatRespArray, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserChats not implemented")
}
func (*UnimplementedChatServer) MarkMessagesRead(context.Context, *MarkMessagesReadReq) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MarkMessagesRead not implemented")
}
func (*UnimplementedChatServer) CreateMessage(context.Context, *CreateMessageReq) (*MessageResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateMessage not implemented")
}
func (*UnimplementedChatServer) DeleteMessage(context.Context, *Id) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteMessage not implemented")
}
func (*UnimplementedChatServer) GetLastNMessages(context.Context, *GetLastNMessagesReq) (*MessageRespArray, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLastNMessages not implemented")
}
func (*UnimplementedChatServer) GetNMessagesBefore(context.Context, *GetNMessagesReq) (*MessageRespArray, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNMessagesBefore not implemented")
}

func RegisterChatServer(s *grpc.Server, srv ChatServer) {
	s.RegisterService(&_Chat_serviceDesc, srv)
}

func _Chat_CreateChat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChatCreateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServer).CreateChat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chat.Chat/CreateChat",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServer).CreateChat(ctx, req.(*ChatCreateReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Chat_GetChatById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetChatByIdReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServer).GetChatById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chat.Chat/GetChatById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServer).GetChatById(ctx, req.(*GetChatByIdReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Chat_GetUserChats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Id)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServer).GetUserChats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chat.Chat/GetUserChats",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServer).GetUserChats(ctx, req.(*Id))
	}
	return interceptor(ctx, in, info, handler)
}

func _Chat_MarkMessagesRead_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MarkMessagesReadReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServer).MarkMessagesRead(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chat.Chat/MarkMessagesRead",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServer).MarkMessagesRead(ctx, req.(*MarkMessagesReadReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Chat_CreateMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateMessageReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServer).CreateMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chat.Chat/CreateMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServer).CreateMessage(ctx, req.(*CreateMessageReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Chat_DeleteMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Id)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServer).DeleteMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chat.Chat/DeleteMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServer).DeleteMessage(ctx, req.(*Id))
	}
	return interceptor(ctx, in, info, handler)
}

func _Chat_GetLastNMessages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLastNMessagesReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServer).GetLastNMessages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chat.Chat/GetLastNMessages",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServer).GetLastNMessages(ctx, req.(*GetLastNMessagesReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Chat_GetNMessagesBefore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNMessagesReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServer).GetNMessagesBefore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chat.Chat/GetNMessagesBefore",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServer).GetNMessagesBefore(ctx, req.(*GetNMessagesReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _Chat_serviceDesc = grpc.ServiceDesc{
	ServiceName: "chat.Chat",
	HandlerType: (*ChatServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateChat",
			Handler:    _Chat_CreateChat_Handler,
		},
		{
			MethodName: "GetChatById",
			Handler:    _Chat_GetChatById_Handler,
		},
		{
			MethodName: "GetUserChats",
			Handler:    _Chat_GetUserChats_Handler,
		},
		{
			MethodName: "MarkMessagesRead",
			Handler:    _Chat_MarkMessagesRead_Handler,
		},
		{
			MethodName: "CreateMessage",
			Handler:    _Chat_CreateMessage_Handler,
		},
		{
			MethodName: "DeleteMessage",
			Handler:    _Chat_DeleteMessage_Handler,
		},
		{
			MethodName: "GetLastNMessages",
			Handler:    _Chat_GetLastNMessages_Handler,
		},
		{
			MethodName: "GetNMessagesBefore",
			Handler:    _Chat_GetNMessagesBefore_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/proto/chat/chat.proto",
}
