// Code generated by MockGen. DO NOT EDIT.
// Source: repository.go

// Package mock_board is a generated GoMock package.
package mock_board

import (
	api "github.com/go-park-mail-ru/2020_2_Eternity/api"
	domain "github.com/go-park-mail-ru/2020_2_Eternity/pkg/domain"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockIRepository is a mock of IRepository interface
type MockIRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIRepositoryMockRecorder
}

// MockIRepositoryMockRecorder is the mock recorder for MockIRepository
type MockIRepositoryMockRecorder struct {
	mock *MockIRepository
}

// NewMockIRepository creates a new mock instance
func NewMockIRepository(ctrl *gomock.Controller) *MockIRepository {
	mock := &MockIRepository{ctrl: ctrl}
	mock.recorder = &MockIRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockIRepository) EXPECT() *MockIRepositoryMockRecorder {
	return m.recorder
}

// CreateBoard mocks base method
func (m *MockIRepository) CreateBoard(userId int, b *api.CreateBoard) (*domain.Board, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateBoard", userId, b)
	ret0, _ := ret[0].(*domain.Board)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateBoard indicates an expected call of CreateBoard
func (mr *MockIRepositoryMockRecorder) CreateBoard(userId, b interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateBoard", reflect.TypeOf((*MockIRepository)(nil).CreateBoard), userId, b)
}

// GetBoard mocks base method
func (m *MockIRepository) GetBoard(id int) (*domain.Board, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBoard", id)
	ret0, _ := ret[0].(*domain.Board)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBoard indicates an expected call of GetBoard
func (mr *MockIRepositoryMockRecorder) GetBoard(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBoard", reflect.TypeOf((*MockIRepository)(nil).GetBoard), id)
}

// GetAllBoardsByUser mocks base method
func (m *MockIRepository) GetAllBoardsByUser(username string) ([]domain.Board, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllBoardsByUser", username)
	ret0, _ := ret[0].([]domain.Board)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllBoardsByUser indicates an expected call of GetAllBoardsByUser
func (mr *MockIRepositoryMockRecorder) GetAllBoardsByUser(username interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllBoardsByUser", reflect.TypeOf((*MockIRepository)(nil).GetAllBoardsByUser), username)
}

// CheckOwner mocks base method
func (m *MockIRepository) CheckOwner(userId, boardId int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckOwner", userId, boardId)
	ret0, _ := ret[0].(error)
	return ret0
}

// CheckOwner indicates an expected call of CheckOwner
func (mr *MockIRepositoryMockRecorder) CheckOwner(userId, boardId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckOwner", reflect.TypeOf((*MockIRepository)(nil).CheckOwner), userId, boardId)
}

// AttachPin mocks base method
func (m *MockIRepository) AttachPin(boardId, pinId int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AttachPin", boardId, pinId)
	ret0, _ := ret[0].(error)
	return ret0
}

// AttachPin indicates an expected call of AttachPin
func (mr *MockIRepositoryMockRecorder) AttachPin(boardId, pinId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AttachPin", reflect.TypeOf((*MockIRepository)(nil).AttachPin), boardId, pinId)
}

// DetachPin mocks base method
func (m *MockIRepository) DetachPin(boardId, pinId int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DetachPin", boardId, pinId)
	ret0, _ := ret[0].(error)
	return ret0
}

// DetachPin indicates an expected call of DetachPin
func (mr *MockIRepositoryMockRecorder) DetachPin(boardId, pinId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DetachPin", reflect.TypeOf((*MockIRepository)(nil).DetachPin), boardId, pinId)
}
