name: Deploy

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master ]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.14.x

    - name: Checkout code
      uses: actions/checkout@v2

#    - name: Run linters
#      run: make lint
#
    - name: Golangci-lint
      uses: golangci/golangci-lint-action@v2
      with:
        # Required: the version of golangci-lint is required and must be specified without patch version: we always use the latest patch version.
        version: v1.29

        # Optional: working directory, useful for monorepos
        # working-directory: somedir

        # Optional: golangci-lint command line arguments.
        # args: --issues-exit-code=0

        # Optional: show only new issues if it's a pull request. The default value is `false`.
        # only-new-issues: true

#    - name: Run tests
#      run: make test

    - name: Build
      run: make build

    - name: Upload build results
      uses: actions/upload-artifact@v1
      with:
        name: bin-ci
        path: ./build/bin


  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download binary
        uses: actions/download-artifact@v1
        with:
          name: bin-ci

      - name: Transfer bin files to server
        uses: appleboy/scp-action@v0.0.10
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          source: "bin-ci/"
          target: "/home/ubuntu/pinterest-backend/build/"

      - name: Restart service
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          script: chmod -R +x /home/ubuntu/pinterest-backend/build/bin-ci &&
                  cd /home/ubuntu/pinterest-backend &&
                  ./scripts/deploy/restart.sh
