name: Deploy

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master ]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.14.x

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run linters
      run: make lint

#    - name: Run tests
#      run: make test

    - name: Build
      run: make build

    - name: Upload build results
      uses: actions/upload-artifact@v1
      with:
        name: binary
        path: ./build/bin


  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download binary
        uses: actions/download-artifact@v1
        with:
          name: binary

      - name: Transfer bin files to server
        uses: appleboy/scp-action@v0.0.10
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          source: "binary/"
          target: "/home/ubuntu/pinterest-backend/build/bin-ci/"

      - name: Restart service
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          script: cd /home/ubuntu/pinterest-backend/build/bin-ci; chmod -R +x ./; ./restart.sh
